apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tridentyauditor.fullname" . }}-config
  labels:
    {{- include "tridentyauditor.labels" . | nindent 4 }}
data:
  TRIDENTY_ENVIRONMENT: {{ .Values.env.environment | quote }}
